#!/usr/bin/env sh

args=()

if [ ! "$1" ]; then
  args+=(--entrypoint /bin/bash)
fi

docker run -it --rm \
  -v "${HOME}/.aws:/root/.aws" \
  -v "$(pwd)/tmp:/tmp" \
  --workdir "/tmp" \
  --log-driver none \
  --name aws \
  "${args[@]}" \
  amazon/aws-cli "$@"
