#!/usr/bin/env sh

if [[ -n $(git status --porcelain) ]];
then
  if [[ $(git rev-parse --abbrev-ref HEAD) == "main" ]];
  then
    echo 'Uncommitted files present on main. You can clean it with:'
    echo 'git checkout .'
    exit 1
  fi

  git add .
  git commit -am "WIP"
fi

date=$(date '+%Y-%m-%d--%H-%M')
title=$(echo "${date}--${@}" | tr ' ' '-')

cat > .git/hooks/pre-push<<- "EOM"
#!/bin/sh

main_branch='master'

policy='[Policy] Never force push or delete the experiment branch! (Prevented with pre-push hook.)'

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

push_command=$(ps -ocommand= -p $PPID)

is_destructive='push|force|delete|\-f'

do_exit(){
  echo $policy
  exit 1
}

if [[ $push_command =~ $is_destructive ]] && [ $current_branch != $main_branch ]; then
  do_exit
fi

unset do_exit

exit 0
EOM

chmod +x .git/hooks/pre-push

git checkout main
git pull
git checkout -b $title
