#!/usr/bin/env sh

args=()

if [ ! "$1" ]; then
  args+=(--entrypoint /bin/bash)
fi

docker run -it --rm \
  -v "$(pwd)/tmp:/tmp" \
  --workdir "/tmp" \
  --log-driver none \
  --name node19 \
  "${args[@]}" \
  node:19-bullseye-slim "$@"
